"""add energy usage to chat sessions

Revision ID: 123f33be6f8b
Revises: c6e120bd1100
Create Date: 2026-09-29 00:56:58.630713

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "123f33be6f8b"
down_revision: str | Sequence[str] | None = "c6e120bd1100"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """
    Add energy-usage memory to AI chat sessions.

    Important:
    This migration intentionally does NOT modify the users
    table. The users table changes generated by Alembic were
    caused by incomplete model metadata during autogenerate.
    """

    # Customer's monthly electricity consumption.
    # One electricity unit is treated as one kWh.
    op.add_column(
        "chat_sessions",
        sa.Column(
            "monthly_units",
            sa.Float(),
            nullable=True,
        ),
    )

    # JSON-serialized appliance usage information.
    #
    # Example:
    # [
    #     {
    #         "appliance": "fan",
    #         "quantity": 2,
    #         "wattage": 75,
    #         "hours_per_day": 8
    #     }
    # ]
    op.add_column(
        "chat_sessions",
        sa.Column(
            "appliance_usage_json",
            sa.Text(),
            nullable=True,
        ),
    )


def downgrade() -> None:
    """
    Remove only the columns introduced by this migration.
    """

    op.drop_column(
        "chat_sessions",
        "appliance_usage_json",
    )

    op.drop_column(
        "chat_sessions",
        "monthly_units",
    )
