"""add crm fields to chat sessions

Revision ID: 12b92ec23ea1
Revises: 12d33cb50fb7
Create Date: 2026-09-26 07:46:14.258913

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "12b92ec23ea1"
down_revision: str | Sequence[str] | None = "12d33cb50fb7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "chat_sessions",
        sa.Column("customer_name", sa.String(length=100), nullable=True),
    )
    op.add_column(
        "chat_sessions",
        sa.Column("customer_phone", sa.String(length=30), nullable=True),
    )
    op.add_column(
        "chat_sessions",
        sa.Column("customer_email", sa.String(length=150), nullable=True),
    )
    op.add_column(
        "chat_sessions",
        sa.Column("customer_city", sa.String(length=100), nullable=True),
    )
    op.add_column(
        "chat_sessions", sa.Column("wants_sales_contact", sa.Boolean(), nullable=True)
    )
    op.add_column("chat_sessions", sa.Column("lead_id", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chat_sessions", "lead_id")
    op.drop_column("chat_sessions", "wants_sales_contact")
    op.drop_column("chat_sessions", "customer_city")
    op.drop_column("chat_sessions", "customer_email")
    op.drop_column("chat_sessions", "customer_phone")
    op.drop_column("chat_sessions", "customer_name")
    # ### end Alembic commands ###
