"""add lead qualification fields

Revision ID: 2ed4543ad46f
Revises: 12b92ec23ea1
Create Date: 2026-09-27 21:59:21.048233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ed4543ad46f'
down_revision: Union[str, Sequence[str], None] = '12b92ec23ea1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('qualification_score', sa.Integer(), nullable=True))
    op.add_column('leads', sa.Column('qualification_level', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'qualification_level')
    op.drop_column('leads', 'qualification_score')
    # ### end Alembic commands ###
