"""create solar packages and package items

Revision ID: 3137d7d3e13e
Revises: 32c1de0a2754
Create Date: 2026-09-26 04:22:23.193734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3137d7d3e13e'
down_revision: Union[str, Sequence[str], None] = '32c1de0a2754'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solar_packages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('system_size_kw', sa.Float(), nullable=False),
    sa.Column('system_type', sa.String(length=50), nullable=False),
    sa.Column('package_price', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solar_packages_system_size_kw'), 'solar_packages', ['system_size_kw'], unique=False)
    op.create_index(op.f('ix_solar_packages_system_type'), 'solar_packages', ['system_type'], unique=False)
    op.create_table('package_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('package_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['solar_packages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('package_id', 'product_id', name='uq_package_product')
    )
    op.create_index(op.f('ix_package_items_package_id'), 'package_items', ['package_id'], unique=False)
    op.create_index(op.f('ix_package_items_product_id'), 'package_items', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_package_items_product_id'), table_name='package_items')
    op.drop_index(op.f('ix_package_items_package_id'), table_name='package_items')
    op.drop_table('package_items')
    op.drop_index(op.f('ix_solar_packages_system_type'), table_name='solar_packages')
    op.drop_index(op.f('ix_solar_packages_system_size_kw'), table_name='solar_packages')
    op.drop_table('solar_packages')
    # ### end Alembic commands ###
