"""add quotation intent to chat sessions

Revision ID: 37038d736e5b
Revises: 98e2e98d8c9b
Create Date: 2026-09-28 06:57:12.432695

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "37038d736e5b"
down_revision: str | Sequence[str] | None = "98e2e98d8c9b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "chat_sessions", sa.Column("wants_quotation", sa.Boolean(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chat_sessions", "wants_quotation")
    # ### end Alembic commands ###
