"""create proposals and proposal items

Revision ID: 98e2e98d8c9b
Revises: c19d796d7572
Create Date: 2026-09-28 02:31:02.968545

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "98e2e98d8c9b"
down_revision: str | Sequence[str] | None = "c19d796d7572"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "proposals",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("lead_id", sa.Integer(), nullable=False),
        sa.Column("package_id", sa.Integer(), nullable=False),
        sa.Column("proposal_number", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("subtotal", sa.Float(), nullable=False),
        sa.Column("discount", sa.Float(), nullable=False),
        sa.Column("total_price", sa.Float(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["lead_id"],
            ["leads.id"],
        ),
        sa.ForeignKeyConstraint(
            ["package_id"],
            ["solar_packages.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_proposals_id"), "proposals", ["id"], unique=False)
    op.create_index(
        op.f("ix_proposals_lead_id"), "proposals", ["lead_id"], unique=False
    )
    op.create_index(
        op.f("ix_proposals_package_id"), "proposals", ["package_id"], unique=False
    )
    op.create_index(
        op.f("ix_proposals_proposal_number"),
        "proposals",
        ["proposal_number"],
        unique=True,
    )
    op.create_table(
        "proposal_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("proposal_id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("product_name", sa.String(length=150), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("unit_price", sa.Float(), nullable=False),
        sa.Column("line_total", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.ForeignKeyConstraint(["proposal_id"], ["proposals.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_proposal_items_id"), "proposal_items", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_proposal_items_product_id"),
        "proposal_items",
        ["product_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_proposal_items_proposal_id"),
        "proposal_items",
        ["proposal_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_proposal_items_proposal_id"), table_name="proposal_items")
    op.drop_index(op.f("ix_proposal_items_product_id"), table_name="proposal_items")
    op.drop_index(op.f("ix_proposal_items_id"), table_name="proposal_items")
    op.drop_table("proposal_items")
    op.drop_index(op.f("ix_proposals_proposal_number"), table_name="proposals")
    op.drop_index(op.f("ix_proposals_package_id"), table_name="proposals")
    op.drop_index(op.f("ix_proposals_lead_id"), table_name="proposals")
    op.drop_index(op.f("ix_proposals_id"), table_name="proposals")
    op.drop_table("proposals")
    # ### end Alembic commands ###
